tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "colordiff"
brew "fzf"
brew "neovim"
brew "thefuck"
brew "tmux"
brew "zsh"
brew "zsh-autosuggestions"

cask "google-chrome"
cask "iterm2"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "rectangle"
cask "spotmenu"
