code-insiders --install-extension arcticicestudio.nord-visual-studio-code && \
code-insiders --install-extension dbaeumer.vscode-eslint && \
code-insiders --install-extension eamodio.gitlens && \
code-insiders --install-extension EditorConfig.EditorConfig && \
code-insiders --install-extension esbenp.prettier-vscode && \
code-insiders --install-extension evan-buss.font-switcher && \
code-insiders --install-extension felixfbecker.php-intellisense && \
code-insiders --install-extension hashicorp.terraform && \
code-insiders --install-extension ms-azuretools.vscode-docker && \
code-insiders --install-extension ms-python.python && \
code-insiders --install-extension rebornix.ruby && \
code-insiders --install-extension rid9.datetime && \
code-insiders --install-extension steditor.line-endings && \
code-insiders --install-extension Tyriar.sort-lines && \
code-insiders --install-extension vscode-icons-team.vscode-icons && \
code-insiders --install-extension vscodevim.vim && \
code-insiders --install-extension wingrunr21.vscode-ruby && \
code-insiders --install-extension wmaurer.change-case && \
code-insiders --install-extension janisdd.vscode-edit-csv && \
code-insiders --install-extension eriklynd.json-tools && \
code-insiders --install-extension suming.react-proptypes-generate
